### ISSUE TITLE
Support multiple values for an option

### ISSUE THREAD

**Issue by hofan41** [hapijs/bossy#36]
Hi,
I would like to begin working on hapijs/lab#285 and in order to support this feature, it is necessary for bossy to somehow parse multiple values in for a given option. I am not quite sure what the appropriate pattern for this might be, either a comma separated list:

```
--reporter lcov,clover,html
```

Or whether they should be specified multiple times but added to an array

```
--reporter lcov --reporter clover --reporter html
```

I would definitely also like to try implementing this feature in bossy myself, so any guidance on enabling this behavior (or if there is another pattern you would like to suggest) I am all ears. 

Thank you!

**Comment by Marsup** [comment]
I vote for the 2nd approach, it is more unixy.

**Comment by sericaia** [comment]
I also prefer the second! :)
Em 13/06/2015 11:10, "Nicolas Morel" <notifications@github.com> escreveu:

**Comment by hofan41** [comment]
It seems like this functionality is already enabled via line 126-131:

```javascript
            if (flags[name]) {
                flags[name] = [].concat(flags[name], value);
            }
            else {
                flags[name] = value;
            }
```

This currently only supports non-falsey values, so I will fix this "bug" and submit a PR.

**Comment by hofan41** [comment]
Another interesting dilemma, it seems number, range, and string types should allow for multiple values, with boolean, it seems like that should be disallowed. Agree?

**Comment by hofan41** [comment]
Another dilemma that presents itself is that sometimes the resultant value could be an array, and sometimes it could be a single value. 

Should we actually introduce an explicit option specifying whether a value can contain multiple values or not? And if it is multiple, it will always be an array. If it is not a multiple, then it will always be a single value.

**Comment by sericaia** [comment]
Sorry, I've closed this with the PR. I think I prefer not to have an explicit option.

**Comment by hofan41** [comment]
It would become rather verbose to check for the presence of a value when there are 3 things a value could be: null, array, single value

```javascript
if ( example.reporter == 'lcov' || example.reporter.indexOf('lcov') != -1 ) 
```

The benefit of the explicit option would be to reduce logic like this from appearing whenever a flag can have multiple values.

**Comment by walling** [comment]
I just want to voice my support for this feature. My use case is to run the tests on a CI service and:

1. Generate JUnit XML that the CI service can analyse
2. Generate HTML coverage report to display in browser

I think it would be nice to support reporter/output pairs to get one report in one file, another report in another file and maybe a third in the console. Something along those lines.

**Comment by sericaia** [comment]
Hello @hofan41,

If you plan to do something like the following, just go ahead.

```javascript
--vodoo --multiple xptoVar1 --vodoo --multiple xptoVar2
```

**Comment by Marsup** [comment]
This doesn't look very understandable. What about adding a flag (`multiple` ?) to the options of switches ? It would default to false to keep from breaking changes, if it is true the value will always be null or an array, if it is false business as usual, or latest declared value, I don't know what's the current behavior.

**Comment by hofan41** [comment]
@Marsup that is what I was suggesting. Sorry if I confused anybody regarding my ask for a multiple option, it is via the api configuration and not from the cli. 

I disagree with the suggestion that if the `multiple` option is false, then it defaults to original behavior. This is because I would also like the falseness of `multiple` to imply the value will always be the value specified in `type`. If a switch between explicit/original behavior is what you actually want, maybe we can also add a `strict` option.

**Comment by Marsup** [comment]
I don't understand what you mean, when false, it'll never be an array, it'll do whatever the library currently does.

**Comment by hofan41** [comment]
@Marsup bossy has always unofficially supported multiple values even before this issue was created. Therefore, if we allow the library to do what it already does, values can be an array, single value, or null.

**Comment by Marsup** [comment]
Oh sorry then, very weird default behavior, maybe it's worth a breaking change ?

**Comment by hofan41** [comment]
I think it is worth it. In that case this issue might need to be moved to a new milestone. My latest PR implements the `multiple` option as the breaking version, where true implies array/null, and false implies `type`/null.
