### ISSUE TITLE
Don't require short form

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/bossy#45]
The documentation says:

> The definition object should be structured with each object key representing the short form of an available command line argument.

However sometimes it's not easy to find a letter for the long form when the letter is already in use for an other option. Or sometimes I just don't want to allow short form for verbosity.

At the moment if I don't specify the short form, then usage information is wrong (`-something` instead of `--something`):

```javascript
const definition = {
  help: {
    description: 'Show help',
    alias: 'h',
    type: 'boolean'
  },
  something: {
    description: 'Do something',
    type: 'boolean'
  }
};
```

```
Options:                 

  -h, --help    Show help
  -something    Do something
```

Another good example is lab. The definition in lab doesn't even follow what is in the documentation (use short form for definition object keys):

https://github.com/hapijs/lab/blob/master/lib/cli.js#L129

I think it would make more sense to use the long form as object keys.

**Comment by sericaia** [comment]
Right now you are able to use 'something' if you want, by specifying it in the alias. You could also send an array of possibilities to alias.
See this example from lab https://github.com/hapijs/lab/blob/master/lib/cli.js#L182

**Comment by gergoerdosi** [comment]
The example above works, I can use `--something`. But there are two problems:

1. In that case `Bossy.usage()` displays it in the wrong way (one `-` instead of two).

  * Incorrect: `-help    Show help`
  * Correct: `--help    Show help`

2. Documentation (and / or the underlying code) is misleading. The documentation says that the key in the definition has to be the short format. But as I explained above, some long options don't have a short format, and for example `lab` uses the long format as keys which goes against the documentation.

I suggest to consider using the long format as a key instead of the short format. Usually all short options have a long format, but not all long options have a short format.

**Comment by gergoerdosi** [comment]
Actually, I will send a PR to fix what I think are the issues, easier to discuss that way.

**Comment by gergoerdosi** [comment]
Checked the code, but it requires a lot of work to handle this properly. Closing this issue for now, I will get back to it when I will have more time. For now I will just use both a short and a long option in my code.
